import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const W=96,H=36,D=96,seed=84721;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x91b7c4); scene.fog=new THREE.Fog(0x91b7c4,42,145);
const camera=new THREE.PerspectiveCamera(75,innerWidth/innerHeight,.05,220); camera.position.set(48,22,48);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setSize(innerWidth,innerHeight); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.15; document.body.prepend(renderer.domElement);
const hemi=new THREE.HemisphereLight(0xd9efff,0x4b4339,1.5); scene.add(hemi);
const sun=new THREE.DirectionalLight(0xfff1d0,3.2); sun.position.set(-45,80,25); sun.castShadow=true; sun.shadow.mapSize.set(2048,2048); sun.shadow.camera.left=-80;sun.shadow.camera.right=80;sun.shadow.camera.top=80;sun.shadow.camera.bottom=-80; scene.add(sun);
const blocks={grass:0x687d52,dirt:0x654b35,stone:0x777b78,sand:0xc9bb8b,wood:0x76563a,leaves:0x405e3d,plank:0x9a764d,glass:0x9ac8d4};
const geo=new THREE.BoxGeometry(1,1,1); const mats={}; for(const [k,c] of Object.entries(blocks)){mats[k]=new THREE.MeshStandardMaterial({color:c,roughness:k==='glass'?.18:.86,metalness:0,transparent:k==='glass',opacity:k==='glass'?.5:1});}
const world=new Map(); const group=new THREE.Group(); scene.add(group);
function noise(x,z){let n=Math.sin(x*12.9898+z*78.233+seed)*43758.5453; return n-Math.floor(n)}
function key(x,y,z){return `${x},${y},${z}`} function height(x,z){return Math.max(3,Math.floor(7+Math.sin(x*.075)*2+Math.cos(z*.09)*2+Math.sin((x+z)*.035)*3+noise(x,z)*2))}
function addBlock(x,y,z,type){const k=key(x,y,z); if(world.has(k))return; const m=new THREE.Mesh(geo,mats[type]||mats.stone);m.position.set(x+.5,y+.5,z+.5);m.castShadow=true;m.receiveShadow=true;m.userData={x,y,z,type};group.add(m);world.set(k,m)}
function removeBlock(x,y,z){const m=world.get(key(x,y,z));if(!m)return;group.remove(m);world.delete(key(x,y,z))}
let count=0; for(let x=0;x<W;x++)for(let z=0;z<D;z++){const h=height(x,z);for(let y=0;y<=h;y++){let t=y===h?'grass':y>h-4?'dirt':'stone';if(y<1)t='stone';addBlock(x,y,z,t);count++} if(noise(x*2,z*2)>.78&&h>7){for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++)for(let dy=1;dy<=3;dy++)if(Math.abs(dx)+Math.abs(dz)<3)addBlock(x+dx,h+dy,z+dz,'leaves');for(let y=1;y<=4;y++)addBlock(x,h+y,z,'wood')}}
const ray=new THREE.Raycaster(); const mouse=new THREE.Vector2(0,0); let selected='grass',locked=false,velY=0,onGround=false; const keys={};
const types=['grass','dirt','stone','sand','wood','leaves','plank','glass'];
const hot=document.querySelector('#hotbar'); hot.innerHTML=types.map((t,i)=>`<div class="slot ${i===0?'sel':''}" data-type="${t}"><span>${i+1}</span><div class="swatch ${t}"></div></div>`).join('');
hot.addEventListener('click',e=>{const s=e.target.closest('.slot');if(!s)return;selected=s.dataset.type;document.querySelectorAll('.slot').forEach(x=>x.classList.toggle('sel',x===s))});
function hit(){ray.setFromCamera(mouse,camera);const hits=ray.intersectObjects(group.children,false);return hits[0]}
function act(button){const h=hit();if(!h)return;const b=h.object.userData;if(button===0){removeBlock(b.x,b.y,b.z)}else{const n=h.face.normal;addBlock(b.x+Math.round(n.x),b.y+Math.round(n.y),b.z+Math.round(n.z),selected)}}
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code.startsWith('Digit')){const i=+e.code.slice(5)-1;if(types[i]){selected=types[i];document.querySelectorAll('.slot').forEach((s,j)=>s.classList.toggle('sel',j===i))}}if(e.code==='Escape'&&locked){document.exitPointerLock()}});addEventListener('keyup',e=>keys[e.code]=false);
renderer.domElement.addEventListener('click',()=>{if(!locked)renderer.domElement.requestPointerLock()}); renderer.domElement.addEventListener('mousedown',e=>{if(locked)act(e.button)}); document.addEventListener('pointerlockchange',()=>{locked=document.pointerLockElement===renderer.domElement;document.querySelector('#pause').classList.toggle('hidden',locked);document.querySelector('#hint').style.opacity=locked?'.15':'1'}); document.addEventListener('mousemove',e=>{if(!locked)return;camera.rotation.y-=e.movementX*.0022;camera.rotation.x-=e.movementY*.0022;camera.rotation.x=Math.max(-1.48,Math.min(1.48,camera.rotation.x))});
const clock=new THREE.Clock(); let last=performance.now(),frames=0,fps=60;
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05);let speed=keys.ShiftLeft?10:5.2;const dir=new THREE.Vector3();if(keys.KeyW)dir.z-=1;if(keys.KeyS)dir.z+=1;if(keys.KeyA)dir.x-=1;if(keys.KeyD)dir.x+=1;dir.normalize().applyAxisAngle(new THREE.Vector3(0,1,0),camera.rotation.y);camera.position.addScaledVector(dir,speed*dt);if(keys.Space&&onGround){velY=8;onGround=false}velY-=22*dt;camera.position.y+=velY*dt;const ground=height(Math.floor(camera.position.x),Math.floor(camera.position.z))+1.65;if(camera.position.y<ground){camera.position.y=ground;velY=0;onGround=true}camera.position.x=Math.max(1,Math.min(W-1,camera.position.x));camera.position.z=Math.max(1,Math.min(D-1,camera.position.z));sun.position.x=Math.sin(performance.now()*.00003)*70;sun.position.z=Math.cos(performance.now()*.00003)*70;renderer.render(scene,camera);frames++;if(performance.now()-last>1000){fps=frames;frames=0;last=performance.now();document.querySelector('#stats').textContent=`FPS ${fps} · BLOCKS ${world.size.toLocaleString()}`;document.querySelector('#blockInfo').textContent=`Selected: ${selected.toUpperCase()}`}}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
let p=0;const bar=document.querySelector('#loadBar'),text=document.querySelector('#loadText');const timer=setInterval(()=>{p=Math.min(100,p+9);bar.style.width=p+'%';text.textContent=p<40?'Generating terrain…':p<75?'Lighting the world…':'Finalising atmosphere…';if(p===100){clearInterval(timer);document.querySelector('#loading').style.opacity='0';setTimeout(()=>document.querySelector('#loading').remove(),700)}},70);
loop();
