import * as THREE from 'three';
import { PointerLockControls } from 'three/addons/controls/PointerLockControls.js';

const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fb9c0);scene.fog=new THREE.Fog(0x9fb9c0,38,150);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,250);camera.position.set(0,18,10);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;document.body.appendChild(renderer.domElement);
const controls=new PointerLockControls(camera,document.body);scene.add(controls.object);
const hemi=new THREE.HemisphereLight(0xd8f2ff,0x4b392b,1.7);scene.add(hemi);
const sun=new THREE.DirectionalLight(0xfff2d4,3.5);sun.position.set(-45,75,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-70;sun.shadow.camera.right=70;sun.shadow.camera.top=70;sun.shadow.camera.bottom=-70;sun.shadow.bias=-.0005;scene.add(sun);
const blocks={grass:0x718d5d,dirt:0x735338,stone:0x7e807d,sand:0xc9bc8c,wood:0x805d3b,leaves:0x466d42,glass:0x9ed5dc,plank:0xa5794e};const names=Object.keys(blocks);let selected=0;const world=new Map(),meshes=new Map();const key=(x,y,z)=>`${x},${y},${z}`;
function noise(x,z){let n=Math.sin(x*127.1+z*311.7)*43758.5453;return n-Math.floor(n)}
function height(x,z){return Math.floor(7+Math.sin(x*.065)*3+Math.cos(z*.052)*3+Math.sin((x+z)*.025)*5+noise(x,z)*2)}
const cube=new THREE.BoxGeometry(1,1,1);const mats={};for(const [n,c] of Object.entries(blocks))mats[n]=new THREE.MeshStandardMaterial({color:c,roughness:n==='glass'?.18:.88,metalness:0,transparent:n==='glass',opacity:n==='glass'?.42:1});
function setBlock(x,y,z,type){world.set(key(x,y,z),type)}
function gen(){const R=45;for(let x=-R;x<=R;x++)for(let z=-R;z<=R;z++){const h=height(x,z);for(let y=0;y<=h;y++){let t=y===h?(h<9?'sand':'grass'):(y>h-4?'dirt':'stone');setBlock(x,y,z,t)}if(h>9&&Math.abs(x)<40&&Math.abs(z)<40&&noise(x*2,z*2)>.84)tree(x,h+1,z)}}
function tree(x,y,z){for(let i=0;i<5;i++)setBlock(x,y+i,z,'wood');for(let dx=-2;dx<=2;dx++)for(let dz=-2;dz<=2;dz++)for(let dy=2;dy<=4;dy++)if(Math.abs(dx)+Math.abs(dz)+Math.max(0,dy-3)<4)setBlock(x+dx,y+dy,z+dz,'leaves')}
function exposed(x,y,z){return !world.has(key(x+1,y,z))||!world.has(key(x-1,y,z))||!world.has(key(x,y+1,z))||!world.has(key(x,y-1,z))||!world.has(key(x,y,z+1))||!world.has(key(x,y,z-1))}
function build(){for(const m of meshes.values())scene.remove(m);meshes.clear();for(const [k,t] of world){const [x,y,z]=k.split(',').map(Number);if(!exposed(x,y,z))continue;const m=new THREE.Mesh(cube,mats[t]);m.position.set(x+.5,y+.5,z+.5);m.castShadow=t!=='glass';m.receiveShadow=true;m.userData={x,y,z,type:t};scene.add(m);meshes.set(k,m)}}
function hotbar(){const h=document.querySelector('#hotbar');h.className='hot';h.innerHTML=names.map((n,i)=>`<div class="slot ${i===selected?'sel':''}"><em>${i+1}</em><div class="cube ${n}"></div></div>`).join('')}
gen();build();hotbar();
const keys={};addEventListener('keydown',e=>{keys[e.code]=true;if(e.code.startsWith('Digit')){const n=+e.code.slice(5)-1;if(n>=0&&n<names.length){selected=n;hotbar()}}});addEventListener('keyup',e=>keys[e.code]=false);
let velY=0,onGround=false;function movement(dt){const speed=(keys.ShiftLeft?10:5)*dt;let f=0,s=0;if(keys.KeyW)f++;if(keys.KeyS)f--;if(keys.KeyD)s++;if(keys.KeyA)s--;if(f||s){const v=new THREE.Vector3(s,0,-f).normalize().multiplyScalar(speed);controls.moveRight(v.x);controls.moveForward(v.z)}velY-=22*dt;camera.position.y+=velY*dt;if(camera.position.y<height(Math.floor(camera.position.x),Math.floor(camera.position.z))+1.7){camera.position.y=height(Math.floor(camera.position.x),Math.floor(camera.position.z))+1.7;velY=0;onGround=true}else onGround=false;if(keys.Space&&onGround){velY=8;onGround=false}}
addEventListener('mousedown',e=>{if(!controls.isLocked){controls.lock();return}const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(0,0),camera);const hit=ray.intersectObjects([...meshes.values()])[0];if(!hit)return;const p=hit.object.userData;if(e.button===0){world.delete(key(p.x,p.y,p.z));build()}else if(e.button===2){const n=hit.face.normal;const x=p.x+n.x,y=p.y+n.y,z=p.z+n.z;if(!world.has(key(x,y,z))){setBlock(x,y,z,names[selected]);build()}}});addEventListener('contextmenu',e=>e.preventDefault());
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
controls.addEventListener('lock',()=>document.querySelector('#help').style.opacity='.25');controls.addEventListener('unlock',()=>document.querySelector('#help').style.opacity='1');
let last=performance.now(),frames=0,fps=60;function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;movement(dt);sun.position.x=Math.sin(now*.00003)*60;sun.position.z=Math.cos(now*.00003)*60;frames++;if(now%500<20){fps=Math.round(frames*1000/(now-(animate.t||now-500)));frames=0;animate.t=now;document.querySelector('#debug').textContent=`${fps} FPS · ${world.size.toLocaleString()} blocks`}renderer.render(scene,camera)}animate(performance.now());setTimeout(()=>{const l=document.querySelector('#loading');l.style.opacity=0;setTimeout(()=>l.remove(),800)},900);
